#pragma once

#define ANTI_CHEAT_DEVICE 0x8000

#define IOCTL_ANTI_CHEAT_SCAN_HOOK CTL_CODE(ANTI_CHEAT_DEVICE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)

struct MyInfo {
  PVOID start;
  PVOID end;
  PVOID deviceControl;
};
